# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech

defmodule Nomad.Connection do
  @moduledoc """
  Handle Tesla connections for Nomad.
  """

  use Tesla

  # Add any middleware here (authentication)
  plug Tesla.Middleware.Headers, [{"user-agent", "Elixir"}]
  plug Tesla.Middleware.EncodeJson, engine: Poison

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client
  def new do
    Tesla.client([
      {Tesla.Middleware.BaseUrl, base_url()}
    ])
  end

  def new(address) do
    Tesla.client([
      {Tesla.Middleware.BaseUrl, address <> "/v1"}
    ])
  end

  defp base_url() do
    if System.get_env("NOMAD_ADDR") != "" do
      System.get_env("NOMAD_ADDR") <> "/v1"
    else
      "http://127.0.0.1:4646/v1"
    end
  end
end
