# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.AclToken do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AccessorID,
    :CreateIndex,
    :CreateTime,
    :ExpirationTTL,
    :ExpirationTime,
    :Global,
    :ModifyIndex,
    :Name,
    :Policies,
    :Roles,
    :SecretID,
    :Type
  ]

  @type t :: %__MODULE__{
    :AccessorID => String.t | nil,
    :CreateIndex => integer() | nil,
    :CreateTime => DateTime.t | nil,
    :ExpirationTTL => integer() | nil,
    :ExpirationTime => DateTime.t | nil,
    :Global => boolean() | nil,
    :ModifyIndex => integer() | nil,
    :Name => String.t | nil,
    :Policies => [String.t] | nil,
    :Roles => [Nomad.Model.AclTokenRoleLink.t] | nil,
    :SecretID => String.t | nil,
    :Type => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AclToken do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Roles, :list, Nomad.Model.AclTokenRoleLink, options)
  end
end

