# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.AclPolicy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CreateIndex,
    :Description,
    :JobACL,
    :ModifyIndex,
    :Name,
    :Rules
  ]

  @type t :: %__MODULE__{
    :CreateIndex => integer() | nil,
    :Description => String.t | nil,
    :JobACL => Nomad.Model.JobAcl.t | nil,
    :ModifyIndex => integer() | nil,
    :Name => String.t | nil,
    :Rules => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AclPolicy do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JobACL, :struct, Nomad.Model.JobAcl, options)
  end
end

