# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.Affinity do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :LTarget,
    :Operand,
    :RTarget,
    :Weight
  ]

  @type t :: %__MODULE__{
    :LTarget => String.t | nil,
    :Operand => String.t | nil,
    :RTarget => String.t | nil,
    :Weight => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Affinity do
  def decode(value, _options) do
    value
  end
end

