# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.AllocatedTaskResources do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Cpu",
    :"Devices",
    :"Memory",
    :"Networks"
  ]

  @type t :: %__MODULE__{
    :"Cpu" => Nomad.Model.AllocatedCpuResources.t | nil,
    :"Devices" => [Nomad.Model.AllocatedDeviceResource.t] | nil,
    :"Memory" => Nomad.Model.AllocatedMemoryResources.t | nil,
    :"Networks" => [Nomad.Model.NetworkResource.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AllocatedTaskResources do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Cpu", :struct, Nomad.Model.AllocatedCpuResources, options)
    |> deserialize(:"Devices", :list, Nomad.Model.AllocatedDeviceResource, options)
    |> deserialize(:"Memory", :struct, Nomad.Model.AllocatedMemoryResources, options)
    |> deserialize(:"Networks", :list, Nomad.Model.NetworkResource, options)
  end
end

