# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.AllocStopResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalID,
    :Index
  ]

  @type t :: %__MODULE__{
    :EvalID => String.t | nil,
    :Index => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AllocStopResponse do
  def decode(value, _options) do
    value
  end
end

