# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.AllocatedResources do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Shared,
    :Tasks
  ]

  @type t :: %__MODULE__{
    :Shared => Nomad.Model.AllocatedSharedResources.t | nil,
    :Tasks => %{optional(String.t) => Nomad.Model.AllocatedTaskResources.t} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AllocatedResources do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Shared, :struct, Nomad.Model.AllocatedSharedResources, options)
    |> deserialize(:Tasks, :map, Nomad.Model.AllocatedTaskResources, options)
  end
end

