# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.AllocationMetric do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AllocationTime",
    :"ClassExhausted",
    :"ClassFiltered",
    :"CoalescedFailures",
    :"ConstraintFiltered",
    :"DimensionExhausted",
    :"NodesAvailable",
    :"NodesEvaluated",
    :"NodesExhausted",
    :"NodesFiltered",
    :"QuotaExhausted",
    :"ResourcesExhausted",
    :"ScoreMetaData",
    :"Scores"
  ]

  @type t :: %__MODULE__{
    :"AllocationTime" => integer() | nil,
    :"ClassExhausted" => %{optional(String.t) => integer()} | nil,
    :"ClassFiltered" => %{optional(String.t) => integer()} | nil,
    :"CoalescedFailures" => integer() | nil,
    :"ConstraintFiltered" => %{optional(String.t) => integer()} | nil,
    :"DimensionExhausted" => %{optional(String.t) => integer()} | nil,
    :"NodesAvailable" => %{optional(String.t) => integer()} | nil,
    :"NodesEvaluated" => integer() | nil,
    :"NodesExhausted" => integer() | nil,
    :"NodesFiltered" => integer() | nil,
    :"QuotaExhausted" => [String.t] | nil,
    :"ResourcesExhausted" => %{optional(String.t) => Nomad.Model.Resources.t} | nil,
    :"ScoreMetaData" => [Nomad.Model.NodeScoreMeta.t] | nil,
    :"Scores" => %{optional(String.t) => float()} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AllocationMetric do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ResourcesExhausted", :map, Nomad.Model.Resources, options)
    |> deserialize(:"ScoreMetaData", :list, Nomad.Model.NodeScoreMeta, options)
  end
end

