# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.AllocDeploymentStatus do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Canary",
    :"Healthy",
    :"ModifyIndex",
    :"Timestamp"
  ]

  @type t :: %__MODULE__{
    :"Canary" => boolean() | nil,
    :"Healthy" => boolean() | nil,
    :"ModifyIndex" => integer() | nil,
    :"Timestamp" => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AllocDeploymentStatus do
  def decode(value, _options) do
    value
  end
end

