# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.AllocatedDeviceResource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DeviceIDs",
    :"Name",
    :"Type",
    :"Vendor"
  ]

  @type t :: %__MODULE__{
    :"DeviceIDs" => [String.t] | nil,
    :"Name" => String.t | nil,
    :"Type" => String.t | nil,
    :"Vendor" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.AllocatedDeviceResource do
  def decode(value, _options) do
    value
  end
end

