# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulGatewayTlsConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CipherSuites,
    :Enabled,
    :TLSMaxVersion,
    :TLSMinVersion
  ]

  @type t :: %__MODULE__{
    :CipherSuites => [String.t] | nil,
    :Enabled => boolean() | nil,
    :TLSMaxVersion => String.t | nil,
    :TLSMinVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulGatewayTlsConfig do
  def decode(value, _options) do
    value
  end
end

