# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulExposeConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Path
  ]

  @type t :: %__MODULE__{
    :Path => [Nomad.Model.ConsulExposePath.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulExposeConfig do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Path, :list, Nomad.Model.ConsulExposePath, options)
  end
end

