# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulGatewayProxy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Config,
    :ConnectTimeout,
    :EnvoyDNSDiscoveryType,
    :EnvoyGatewayBindAddresses,
    :EnvoyGatewayBindTaggedAddresses,
    :EnvoyGatewayNoDefaultBind
  ]

  @type t :: %__MODULE__{
    :Config => %{optional(String.t) => any()} | nil,
    :ConnectTimeout => integer() | nil,
    :EnvoyDNSDiscoveryType => String.t | nil,
    :EnvoyGatewayBindAddresses => %{optional(String.t) => Nomad.Model.ConsulGatewayBindAddress.t} | nil,
    :EnvoyGatewayBindTaggedAddresses => boolean() | nil,
    :EnvoyGatewayNoDefaultBind => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulGatewayProxy do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:EnvoyGatewayBindAddresses, :map, Nomad.Model.ConsulGatewayBindAddress, options)
  end
end

