# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulGateway do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Ingress,
    :Mesh,
    :Proxy,
    :Terminating
  ]

  @type t :: %__MODULE__{
    :Ingress => Nomad.Model.ConsulIngressConfigEntry.t | nil,
    :Mesh => any() | nil,
    :Proxy => Nomad.Model.ConsulGatewayProxy.t | nil,
    :Terminating => Nomad.Model.ConsulTerminatingConfigEntry.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulGateway do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Ingress, :struct, Nomad.Model.ConsulIngressConfigEntry, options)
    |> deserialize(:Proxy, :struct, Nomad.Model.ConsulGatewayProxy, options)
    |> deserialize(:Terminating, :struct, Nomad.Model.ConsulTerminatingConfigEntry, options)
  end
end

