# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulIngressListener do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Port,
    :Protocol,
    :Services
  ]

  @type t :: %__MODULE__{
    :Port => integer() | nil,
    :Protocol => String.t | nil,
    :Services => [Nomad.Model.ConsulIngressService.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulIngressListener do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Services, :list, Nomad.Model.ConsulIngressService, options)
  end
end

