# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ConsulSidecarService do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DisableDefaultTCPCheck",
    :"Port",
    :"Proxy",
    :"Tags"
  ]

  @type t :: %__MODULE__{
    :"DisableDefaultTCPCheck" => boolean() | nil,
    :"Port" => String.t | nil,
    :"Proxy" => Nomad.Model.ConsulProxy.t | nil,
    :"Tags" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulSidecarService do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Proxy", :struct, Nomad.Model.ConsulProxy, options)
  end
end

