# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulUpstream do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Datacenter,
    :DestinationName,
    :DestinationNamespace,
    :LocalBindAddress,
    :LocalBindPort,
    :MeshGateway
  ]

  @type t :: %__MODULE__{
    :Datacenter => String.t | nil,
    :DestinationName => String.t | nil,
    :DestinationNamespace => String.t | nil,
    :LocalBindAddress => String.t | nil,
    :LocalBindPort => integer() | nil,
    :MeshGateway => Nomad.Model.ConsulMeshGateway.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulUpstream do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:MeshGateway, :struct, Nomad.Model.ConsulMeshGateway, options)
  end
end

