# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ConsulGatewayProxy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Config",
    :"ConnectTimeout",
    :"EnvoyDNSDiscoveryType",
    :"EnvoyGatewayBindAddresses",
    :"EnvoyGatewayBindTaggedAddresses",
    :"EnvoyGatewayNoDefaultBind"
  ]

  @type t :: %__MODULE__{
    :"Config" => %{optional(String.t) => AnyType} | nil,
    :"ConnectTimeout" => integer() | nil,
    :"EnvoyDNSDiscoveryType" => String.t | nil,
    :"EnvoyGatewayBindAddresses" => %{optional(String.t) => Nomad.Model.ConsulGatewayBindAddress.t} | nil,
    :"EnvoyGatewayBindTaggedAddresses" => boolean() | nil,
    :"EnvoyGatewayNoDefaultBind" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulGatewayProxy do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Config", :map, Nomad.Model.AnyType, options)
    |> deserialize(:"EnvoyGatewayBindAddresses", :map, Nomad.Model.ConsulGatewayBindAddress, options)
  end
end

