# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulConnect do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Gateway,
    :Native,
    :SidecarService,
    :SidecarTask
  ]

  @type t :: %__MODULE__{
    :Gateway => Nomad.Model.ConsulGateway.t | nil,
    :Native => boolean() | nil,
    :SidecarService => Nomad.Model.ConsulSidecarService.t | nil,
    :SidecarTask => Nomad.Model.SidecarTask.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulConnect do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Gateway, :struct, Nomad.Model.ConsulGateway, options)
    |> deserialize(:SidecarService, :struct, Nomad.Model.ConsulSidecarService, options)
    |> deserialize(:SidecarTask, :struct, Nomad.Model.SidecarTask, options)
  end
end

