# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ConsulExposeConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Path"
  ]

  @type t :: %__MODULE__{
    :"Path" => [Nomad.Model.ConsulExposePath.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulExposeConfig do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Path", :list, Nomad.Model.ConsulExposePath, options)
  end
end

