# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulSidecarService do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DisableDefaultTCPCheck,
    :Port,
    :Proxy,
    :Tags
  ]

  @type t :: %__MODULE__{
    :DisableDefaultTCPCheck => boolean() | nil,
    :Port => String.t | nil,
    :Proxy => Nomad.Model.ConsulProxy.t | nil,
    :Tags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulSidecarService do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Proxy, :struct, Nomad.Model.ConsulProxy, options)
  end
end

