# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulExposePath do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ListenerPort,
    :LocalPathPort,
    :Path,
    :Protocol
  ]

  @type t :: %__MODULE__{
    :ListenerPort => String.t | nil,
    :LocalPathPort => integer() | nil,
    :Path => String.t | nil,
    :Protocol => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulExposePath do
  def decode(value, _options) do
    value
  end
end

