# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ConsulIngressConfigEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Listeners,
    :TLS
  ]

  @type t :: %__MODULE__{
    :Listeners => [Nomad.Model.ConsulIngressListener.t] | nil,
    :TLS => Nomad.Model.ConsulGatewayTlsConfig.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ConsulIngressConfigEntry do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Listeners, :list, Nomad.Model.ConsulIngressListener, options)
    |> deserialize(:TLS, :struct, Nomad.Model.ConsulGatewayTlsConfig, options)
  end
end

