# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.CsiVolumeListExternalResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :NextToken,
    :Volumes
  ]

  @type t :: %__MODULE__{
    :NextToken => String.t | nil,
    :Volumes => [Nomad.Model.CsiVolumeExternalStub.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiVolumeListExternalResponse do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Volumes, :list, Nomad.Model.CsiVolumeExternalStub, options)
  end
end

