# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.CsiTopologyRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Preferred,
    :Required
  ]

  @type t :: %__MODULE__{
    :Preferred => [Nomad.Model.CsiTopology.t] | nil,
    :Required => [Nomad.Model.CsiTopology.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiTopologyRequest do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Preferred, :list, Nomad.Model.CsiTopology, options)
    |> deserialize(:Required, :list, Nomad.Model.CsiTopology, options)
  end
end

