# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.CsiVolumeListStub do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AccessMode",
    :"AttachmentMode",
    :"ControllerRequired",
    :"ControllersExpected",
    :"ControllersHealthy",
    :"CreateIndex",
    :"ExternalID",
    :"ID",
    :"ModifyIndex",
    :"Name",
    :"Namespace",
    :"NodesExpected",
    :"NodesHealthy",
    :"PluginID",
    :"Provider",
    :"ResourceExhausted",
    :"Schedulable",
    :"Topologies"
  ]

  @type t :: %__MODULE__{
    :"AccessMode" => String.t | nil,
    :"AttachmentMode" => String.t | nil,
    :"ControllerRequired" => boolean() | nil,
    :"ControllersExpected" => integer() | nil,
    :"ControllersHealthy" => integer() | nil,
    :"CreateIndex" => integer() | nil,
    :"ExternalID" => String.t | nil,
    :"ID" => String.t | nil,
    :"ModifyIndex" => integer() | nil,
    :"Name" => String.t | nil,
    :"Namespace" => String.t | nil,
    :"NodesExpected" => integer() | nil,
    :"NodesHealthy" => integer() | nil,
    :"PluginID" => String.t | nil,
    :"Provider" => String.t | nil,
    :"ResourceExhausted" => DateTime.t | nil,
    :"Schedulable" => boolean() | nil,
    :"Topologies" => [Nomad.Model.CsiTopology.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiVolumeListStub do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Topologies", :list, Nomad.Model.CsiTopology, options)
  end
end

