# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.CsiNodeInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AccessibleTopology,
    :ID,
    :MaxVolumes,
    :RequiresNodeStageVolume,
    :SupportsCondition,
    :SupportsExpand,
    :SupportsStats
  ]

  @type t :: %__MODULE__{
    :AccessibleTopology => Nomad.Model.CsiTopology.t | nil,
    :ID => String.t | nil,
    :MaxVolumes => integer() | nil,
    :RequiresNodeStageVolume => boolean() | nil,
    :SupportsCondition => boolean() | nil,
    :SupportsExpand => boolean() | nil,
    :SupportsStats => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiNodeInfo do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AccessibleTopology, :struct, Nomad.Model.CsiTopology, options)
  end
end

