# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.CsiInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AllocID,
    :ControllerInfo,
    :HealthDescription,
    :Healthy,
    :NodeInfo,
    :PluginID,
    :RequiresControllerPlugin,
    :RequiresTopologies,
    :UpdateTime
  ]

  @type t :: %__MODULE__{
    :AllocID => String.t | nil,
    :ControllerInfo => Nomad.Model.CsiControllerInfo.t | nil,
    :HealthDescription => String.t | nil,
    :Healthy => boolean() | nil,
    :NodeInfo => Nomad.Model.CsiNodeInfo.t | nil,
    :PluginID => String.t | nil,
    :RequiresControllerPlugin => boolean() | nil,
    :RequiresTopologies => boolean() | nil,
    :UpdateTime => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiInfo do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ControllerInfo, :struct, Nomad.Model.CsiControllerInfo, options)
    |> deserialize(:NodeInfo, :struct, Nomad.Model.CsiNodeInfo, options)
  end
end

