# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.CsiMountOptions do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :FSType,
    :MountFlags
  ]

  @type t :: %__MODULE__{
    :FSType => String.t | nil,
    :MountFlags => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiMountOptions do
  def decode(value, _options) do
    value
  end
end

