# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.CsiPluginListStub do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ControllerRequired,
    :ControllersExpected,
    :ControllersHealthy,
    :CreateIndex,
    :ID,
    :ModifyIndex,
    :NodesExpected,
    :NodesHealthy,
    :Provider
  ]

  @type t :: %__MODULE__{
    :ControllerRequired => boolean() | nil,
    :ControllersExpected => integer() | nil,
    :ControllersHealthy => integer() | nil,
    :CreateIndex => integer() | nil,
    :ID => String.t | nil,
    :ModifyIndex => integer() | nil,
    :NodesExpected => integer() | nil,
    :NodesHealthy => integer() | nil,
    :Provider => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.CsiPluginListStub do
  def decode(value, _options) do
    value
  end
end

