# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.DeploymentPromoteRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :All,
    :DeploymentID,
    :Groups,
    :Namespace,
    :Region,
    :SecretID
  ]

  @type t :: %__MODULE__{
    :All => boolean() | nil,
    :DeploymentID => String.t | nil,
    :Groups => [String.t] | nil,
    :Namespace => String.t | nil,
    :Region => String.t | nil,
    :SecretID => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DeploymentPromoteRequest do
  def decode(value, _options) do
    value
  end
end

