# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.DeploymentState do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AutoRevert",
    :"DesiredCanaries",
    :"DesiredTotal",
    :"HealthyAllocs",
    :"PlacedAllocs",
    :"PlacedCanaries",
    :"ProgressDeadline",
    :"Promoted",
    :"RequireProgressBy",
    :"UnhealthyAllocs"
  ]

  @type t :: %__MODULE__{
    :"AutoRevert" => boolean() | nil,
    :"DesiredCanaries" => integer() | nil,
    :"DesiredTotal" => integer() | nil,
    :"HealthyAllocs" => integer() | nil,
    :"PlacedAllocs" => integer() | nil,
    :"PlacedCanaries" => [String.t] | nil,
    :"ProgressDeadline" => integer() | nil,
    :"Promoted" => boolean() | nil,
    :"RequireProgressBy" => DateTime.t | nil,
    :"UnhealthyAllocs" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DeploymentState do
  def decode(value, _options) do
    value
  end
end

