# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.DeploymentAllocHealthRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DeploymentID,
    :HealthyAllocationIDs,
    :Namespace,
    :Region,
    :SecretID,
    :UnhealthyAllocationIDs
  ]

  @type t :: %__MODULE__{
    :DeploymentID => String.t | nil,
    :HealthyAllocationIDs => [String.t] | nil,
    :Namespace => String.t | nil,
    :Region => String.t | nil,
    :SecretID => String.t | nil,
    :UnhealthyAllocationIDs => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DeploymentAllocHealthRequest do
  def decode(value, _options) do
    value
  end
end

