# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.DeploymentUpdateResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DeploymentModifyIndex,
    :EvalCreateIndex,
    :EvalID,
    :LastIndex,
    :RequestTime,
    :RevertedJobVersion
  ]

  @type t :: %__MODULE__{
    :DeploymentModifyIndex => integer() | nil,
    :EvalCreateIndex => integer() | nil,
    :EvalID => String.t | nil,
    :LastIndex => integer() | nil,
    :RequestTime => integer() | nil,
    :RevertedJobVersion => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DeploymentUpdateResponse do
  def decode(value, _options) do
    value
  end
end

