# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.DispatchPayloadConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :File
  ]

  @type t :: %__MODULE__{
    :File => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DispatchPayloadConfig do
  def decode(value, _options) do
    value
  end
end

