# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.DnsConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Options",
    :"Searches",
    :"Servers"
  ]

  @type t :: %__MODULE__{
    :"Options" => [String.t] | nil,
    :"Searches" => [String.t] | nil,
    :"Servers" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DnsConfig do
  def decode(value, _options) do
    value
  end
end

