# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.DrainSpec do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Deadline,
    :IgnoreSystemJobs
  ]

  @type t :: %__MODULE__{
    :Deadline => integer() | nil,
    :IgnoreSystemJobs => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.DrainSpec do
  def decode(value, _options) do
    value
  end
end

