# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.EphemeralDisk do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Migrate,
    :SizeMB,
    :Sticky
  ]

  @type t :: %__MODULE__{
    :Migrate => boolean() | nil,
    :SizeMB => integer() | nil,
    :Sticky => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.EphemeralDisk do
  def decode(value, _options) do
    value
  end
end

