# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.FieldDiff do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Annotations,
    :Name,
    :New,
    :Old,
    :Type
  ]

  @type t :: %__MODULE__{
    :Annotations => [String.t] | nil,
    :Name => String.t | nil,
    :New => String.t | nil,
    :Old => String.t | nil,
    :Type => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.FieldDiff do
  def decode(value, _options) do
    value
  end
end

