# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.FieldDiff do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Annotations",
    :"Name",
    :"New",
    :"Old",
    :"Type"
  ]

  @type t :: %__MODULE__{
    :"Annotations" => [String.t] | nil,
    :"Name" => String.t | nil,
    :"New" => String.t | nil,
    :"Old" => String.t | nil,
    :"Type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.FieldDiff do
  def decode(value, _options) do
    value
  end
end

