# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.FuzzyMatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ID",
    :"Scope"
  ]

  @type t :: %__MODULE__{
    :"ID" => String.t | nil,
    :"Scope" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.FuzzyMatch do
  def decode(value, _options) do
    value
  end
end

