# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.FuzzyMatch do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Scope
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Scope => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.FuzzyMatch do
  def decode(value, _options) do
    value
  end
end

