# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.GaugeValue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Labels",
    :"Name",
    :"Value"
  ]

  @type t :: %__MODULE__{
    :"Labels" => %{optional(String.t) => String.t} | nil,
    :"Name" => String.t | nil,
    :"Value" => float() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.GaugeValue do
  def decode(value, _options) do
    value
  end
end

