# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.GaugeValue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Labels,
    :Name,
    :Value
  ]

  @type t :: %__MODULE__{
    :Labels => %{optional(String.t) => String.t} | nil,
    :Name => String.t | nil,
    :Value => float() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.GaugeValue do
  def decode(value, _options) do
    value
  end
end

