# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobValidateResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DriverConfigValidated",
    :"Error",
    :"ValidationErrors",
    :"Warnings"
  ]

  @type t :: %__MODULE__{
    :"DriverConfigValidated" => boolean() | nil,
    :"Error" => String.t | nil,
    :"ValidationErrors" => [String.t] | nil,
    :"Warnings" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobValidateResponse do
  def decode(value, _options) do
    value
  end
end

