# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobDiff do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Fields,
    :ID,
    :Objects,
    :TaskGroups,
    :Type
  ]

  @type t :: %__MODULE__{
    :Fields => [Nomad.Model.FieldDiff.t] | nil,
    :ID => String.t | nil,
    :Objects => [Nomad.Model.ObjectDiff.t] | nil,
    :TaskGroups => [Nomad.Model.TaskGroupDiff.t] | nil,
    :Type => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobDiff do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Fields, :list, Nomad.Model.FieldDiff, options)
    |> deserialize(:Objects, :list, Nomad.Model.ObjectDiff, options)
    |> deserialize(:TaskGroups, :list, Nomad.Model.TaskGroupDiff, options)
  end
end

