# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Children,
    :CreateIndex,
    :JobID,
    :ModifyIndex,
    :Namespace,
    :Summary
  ]

  @type t :: %__MODULE__{
    :Children => Nomad.Model.JobChildrenSummary.t | nil,
    :CreateIndex => integer() | nil,
    :JobID => String.t | nil,
    :ModifyIndex => integer() | nil,
    :Namespace => String.t | nil,
    :Summary => %{optional(String.t) => Nomad.Model.TaskGroupSummary.t} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobSummary do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Children, :struct, Nomad.Model.JobChildrenSummary, options)
    |> deserialize(:Summary, :map, Nomad.Model.TaskGroupSummary, options)
  end
end

