# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobScaleStatusResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobCreateIndex",
    :"JobID",
    :"JobModifyIndex",
    :"JobStopped",
    :"Namespace",
    :"TaskGroups"
  ]

  @type t :: %__MODULE__{
    :"JobCreateIndex" => integer() | nil,
    :"JobID" => String.t | nil,
    :"JobModifyIndex" => integer() | nil,
    :"JobStopped" => boolean() | nil,
    :"Namespace" => String.t | nil,
    :"TaskGroups" => %{optional(String.t) => Nomad.Model.TaskGroupScaleStatus.t} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobScaleStatusResponse do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"TaskGroups", :map, Nomad.Model.TaskGroupScaleStatus, options)
  end
end

