# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobStabilityRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobID",
    :"JobVersion",
    :"Namespace",
    :"Region",
    :"SecretID",
    :"Stable"
  ]

  @type t :: %__MODULE__{
    :"JobID" => String.t | nil,
    :"JobVersion" => integer() | nil,
    :"Namespace" => String.t | nil,
    :"Region" => String.t | nil,
    :"SecretID" => String.t | nil,
    :"Stable" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobStabilityRequest do
  def decode(value, _options) do
    value
  end
end

