# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobRegisterResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"EvalCreateIndex",
    :"EvalID",
    :"JobModifyIndex",
    :"KnownLeader",
    :"LastContact",
    :"LastIndex",
    :"RequestTime",
    :"Warnings"
  ]

  @type t :: %__MODULE__{
    :"EvalCreateIndex" => integer() | nil,
    :"EvalID" => String.t | nil,
    :"JobModifyIndex" => integer() | nil,
    :"KnownLeader" => boolean() | nil,
    :"LastContact" => integer() | nil,
    :"LastIndex" => integer() | nil,
    :"RequestTime" => integer() | nil,
    :"Warnings" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobRegisterResponse do
  def decode(value, _options) do
    value
  end
end

