# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobDispatchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :JobID,
    :Meta,
    :Payload
  ]

  @type t :: %__MODULE__{
    :JobID => String.t | nil,
    :Meta => %{optional(String.t) => String.t} | nil,
    :Payload => binary() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobDispatchRequest do
  def decode(value, _options) do
    value
  end
end

