# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobVersionsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Diffs,
    :KnownLeader,
    :LastContact,
    :LastIndex,
    :NextToken,
    :RequestTime,
    :Versions
  ]

  @type t :: %__MODULE__{
    :Diffs => [Nomad.Model.JobDiff.t] | nil,
    :KnownLeader => boolean() | nil,
    :LastContact => integer() | nil,
    :LastIndex => integer() | nil,
    :NextToken => String.t | nil,
    :RequestTime => integer() | nil,
    :Versions => [Nomad.Model.Job.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobVersionsResponse do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Diffs, :list, Nomad.Model.JobDiff, options)
    |> deserialize(:Versions, :list, Nomad.Model.Job, options)
  end
end

