# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobPlanResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Annotations",
    :"CreatedEvals",
    :"Diff",
    :"FailedTGAllocs",
    :"JobModifyIndex",
    :"NextPeriodicLaunch",
    :"Warnings"
  ]

  @type t :: %__MODULE__{
    :"Annotations" => Nomad.Model.PlanAnnotations.t | nil,
    :"CreatedEvals" => [Nomad.Model.Evaluation.t] | nil,
    :"Diff" => Nomad.Model.JobDiff.t | nil,
    :"FailedTGAllocs" => %{optional(String.t) => Nomad.Model.AllocationMetric.t} | nil,
    :"JobModifyIndex" => integer() | nil,
    :"NextPeriodicLaunch" => DateTime.t | nil,
    :"Warnings" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobPlanResponse do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Annotations", :struct, Nomad.Model.PlanAnnotations, options)
    |> deserialize(:"CreatedEvals", :list, Nomad.Model.Evaluation, options)
    |> deserialize(:"Diff", :struct, Nomad.Model.JobDiff, options)
    |> deserialize(:"FailedTGAllocs", :map, Nomad.Model.AllocationMetric, options)
  end
end

