# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobVersionsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Diffs",
    :"KnownLeader",
    :"LastContact",
    :"LastIndex",
    :"RequestTime",
    :"Versions"
  ]

  @type t :: %__MODULE__{
    :"Diffs" => [Nomad.Model.JobDiff.t] | nil,
    :"KnownLeader" => boolean() | nil,
    :"LastContact" => integer() | nil,
    :"LastIndex" => integer() | nil,
    :"RequestTime" => integer() | nil,
    :"Versions" => [Nomad.Model.Job.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobVersionsResponse do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Diffs", :list, Nomad.Model.JobDiff, options)
    |> deserialize(:"Versions", :list, Nomad.Model.Job, options)
  end
end

