# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Children",
    :"CreateIndex",
    :"JobID",
    :"ModifyIndex",
    :"Namespace",
    :"Summary"
  ]

  @type t :: %__MODULE__{
    :"Children" => Nomad.Model.JobChildrenSummary.t | nil,
    :"CreateIndex" => integer() | nil,
    :"JobID" => String.t | nil,
    :"ModifyIndex" => integer() | nil,
    :"Namespace" => String.t | nil,
    :"Summary" => %{optional(String.t) => Nomad.Model.TaskGroupSummary.t} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobSummary do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Children", :struct, Nomad.Model.JobChildrenSummary, options)
    |> deserialize(:"Summary", :map, Nomad.Model.TaskGroupSummary, options)
  end
end

