# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobRegisterRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EnforceIndex,
    :EvalPriority,
    :Job,
    :JobModifyIndex,
    :Namespace,
    :PolicyOverride,
    :PreserveCounts,
    :Region,
    :SecretID
  ]

  @type t :: %__MODULE__{
    :EnforceIndex => boolean() | nil,
    :EvalPriority => integer() | nil,
    :Job => Nomad.Model.Job.t | nil,
    :JobModifyIndex => integer() | nil,
    :Namespace => String.t | nil,
    :PolicyOverride => boolean() | nil,
    :PreserveCounts => boolean() | nil,
    :Region => String.t | nil,
    :SecretID => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobRegisterRequest do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Job, :struct, Nomad.Model.Job, options)
  end
end

