# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobDispatchResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DispatchedJobID",
    :"EvalCreateIndex",
    :"EvalID",
    :"JobCreateIndex",
    :"LastIndex",
    :"RequestTime"
  ]

  @type t :: %__MODULE__{
    :"DispatchedJobID" => String.t | nil,
    :"EvalCreateIndex" => integer() | nil,
    :"EvalID" => String.t | nil,
    :"JobCreateIndex" => integer() | nil,
    :"LastIndex" => integer() | nil,
    :"RequestTime" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobDispatchResponse do
  def decode(value, _options) do
    value
  end
end

