# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobChildrenSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Dead",
    :"Pending",
    :"Running"
  ]

  @type t :: %__MODULE__{
    :"Dead" => integer() | nil,
    :"Pending" => integer() | nil,
    :"Running" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobChildrenSummary do
  def decode(value, _options) do
    value
  end
end

