# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobRegisterResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalCreateIndex,
    :EvalID,
    :JobModifyIndex,
    :KnownLeader,
    :LastContact,
    :LastIndex,
    :NextToken,
    :RequestTime,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :EvalCreateIndex => integer() | nil,
    :EvalID => String.t | nil,
    :JobModifyIndex => integer() | nil,
    :KnownLeader => boolean() | nil,
    :LastContact => integer() | nil,
    :LastIndex => integer() | nil,
    :NextToken => String.t | nil,
    :RequestTime => integer() | nil,
    :Warnings => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobRegisterResponse do
  def decode(value, _options) do
    value
  end
end

