# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.JobsParseRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Canonicalize,
    :JobHCL,
    :hclv1
  ]

  @type t :: %__MODULE__{
    :Canonicalize => boolean() | nil,
    :JobHCL => String.t | nil,
    :hclv1 => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobsParseRequest do
  def decode(value, _options) do
    value
  end
end

