# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.JobsParseRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Canonicalize,
    :JobHCL,
    :hclv1
  ]

  @type t :: %__MODULE__{
    :Canonicalize => boolean() | nil,
    :JobHCL => String.t | nil,
    :hclv1 => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.JobsParseRequest do
  def decode(value, _options) do
    value
  end
end

