# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.LogConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MaxFileSizeMB",
    :"MaxFiles"
  ]

  @type t :: %__MODULE__{
    :"MaxFileSizeMB" => integer() | nil,
    :"MaxFiles" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.LogConfig do
  def decode(value, _options) do
    value
  end
end

