# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.MigrateStrategy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"HealthCheck",
    :"HealthyDeadline",
    :"MaxParallel",
    :"MinHealthyTime"
  ]

  @type t :: %__MODULE__{
    :"HealthCheck" => String.t | nil,
    :"HealthyDeadline" => integer() | nil,
    :"MaxParallel" => integer() | nil,
    :"MinHealthyTime" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.MigrateStrategy do
  def decode(value, _options) do
    value
  end
end

