# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.MultiregionStrategy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MaxParallel",
    :"OnFailure"
  ]

  @type t :: %__MODULE__{
    :"MaxParallel" => integer() | nil,
    :"OnFailure" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.MultiregionStrategy do
  def decode(value, _options) do
    value
  end
end

