# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.Multiregion do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Regions,
    :Strategy
  ]

  @type t :: %__MODULE__{
    :Regions => [Nomad.Model.MultiregionRegion.t] | nil,
    :Strategy => Nomad.Model.MultiregionStrategy.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Multiregion do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Regions, :list, Nomad.Model.MultiregionRegion, options)
    |> deserialize(:Strategy, :struct, Nomad.Model.MultiregionStrategy, options)
  end
end

