# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.Namespace do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Capabilities,
    :CreateIndex,
    :Description,
    :Meta,
    :ModifyIndex,
    :Name,
    :Quota
  ]

  @type t :: %__MODULE__{
    :Capabilities => Nomad.Model.NamespaceCapabilities.t | nil,
    :CreateIndex => integer() | nil,
    :Description => String.t | nil,
    :Meta => %{optional(String.t) => String.t} | nil,
    :ModifyIndex => integer() | nil,
    :Name => String.t | nil,
    :Quota => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Namespace do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Capabilities, :struct, Nomad.Model.NamespaceCapabilities, options)
  end
end

