# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.NetworkResource do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CIDR,
    :DNS,
    :Device,
    :DynamicPorts,
    :Hostname,
    :IP,
    :MBits,
    :Mode,
    :ReservedPorts
  ]

  @type t :: %__MODULE__{
    :CIDR => String.t | nil,
    :DNS => Nomad.Model.DnsConfig.t | nil,
    :Device => String.t | nil,
    :DynamicPorts => [Nomad.Model.Port.t] | nil,
    :Hostname => String.t | nil,
    :IP => String.t | nil,
    :MBits => integer() | nil,
    :Mode => String.t | nil,
    :ReservedPorts => [Nomad.Model.Port.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NetworkResource do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:DNS, :struct, Nomad.Model.DnsConfig, options)
    |> deserialize(:DynamicPorts, :list, Nomad.Model.Port, options)
    |> deserialize(:ReservedPorts, :list, Nomad.Model.Port, options)
  end
end

