# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.NodeScoreMeta do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"NodeID",
    :"NormScore",
    :"Scores"
  ]

  @type t :: %__MODULE__{
    :"NodeID" => String.t | nil,
    :"NormScore" => float() | nil,
    :"Scores" => %{optional(String.t) => float()} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeScoreMeta do
  def decode(value, _options) do
    value
  end
end

