# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.NodeDrainUpdateResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :EvalCreateIndex,
    :EvalIDs,
    :LastIndex,
    :NodeModifyIndex,
    :RequestTime
  ]

  @type t :: %__MODULE__{
    :EvalCreateIndex => integer() | nil,
    :EvalIDs => [String.t] | nil,
    :LastIndex => integer() | nil,
    :NodeModifyIndex => integer() | nil,
    :RequestTime => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeDrainUpdateResponse do
  def decode(value, _options) do
    value
  end
end

