# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.NodeResources do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Cpu,
    :Devices,
    :Disk,
    :MaxDynamicPort,
    :Memory,
    :MinDynamicPort,
    :Networks
  ]

  @type t :: %__MODULE__{
    :Cpu => Nomad.Model.NodeCpuResources.t | nil,
    :Devices => [Nomad.Model.NodeDeviceResource.t] | nil,
    :Disk => Nomad.Model.NodeDiskResources.t | nil,
    :MaxDynamicPort => integer() | nil,
    :Memory => Nomad.Model.NodeMemoryResources.t | nil,
    :MinDynamicPort => integer() | nil,
    :Networks => [Nomad.Model.NetworkResource.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeResources do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Cpu, :struct, Nomad.Model.NodeCpuResources, options)
    |> deserialize(:Devices, :list, Nomad.Model.NodeDeviceResource, options)
    |> deserialize(:Disk, :struct, Nomad.Model.NodeDiskResources, options)
    |> deserialize(:Memory, :struct, Nomad.Model.NodeMemoryResources, options)
    |> deserialize(:Networks, :list, Nomad.Model.NetworkResource, options)
  end
end

