# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.NodeReservedResources do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Cpu,
    :Disk,
    :Memory,
    :Networks
  ]

  @type t :: %__MODULE__{
    :Cpu => Nomad.Model.NodeReservedCpuResources.t | nil,
    :Disk => Nomad.Model.NodeReservedDiskResources.t | nil,
    :Memory => Nomad.Model.NodeReservedMemoryResources.t | nil,
    :Networks => Nomad.Model.NodeReservedNetworkResources.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeReservedResources do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Cpu, :struct, Nomad.Model.NodeReservedCpuResources, options)
    |> deserialize(:Disk, :struct, Nomad.Model.NodeReservedDiskResources, options)
    |> deserialize(:Memory, :struct, Nomad.Model.NodeReservedMemoryResources, options)
    |> deserialize(:Networks, :struct, Nomad.Model.NodeReservedNetworkResources, options)
  end
end

