# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.NodeUpdateDrainRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DrainSpec,
    :MarkEligible,
    :Meta,
    :NodeID
  ]

  @type t :: %__MODULE__{
    :DrainSpec => Nomad.Model.DrainSpec.t | nil,
    :MarkEligible => boolean() | nil,
    :Meta => %{optional(String.t) => String.t} | nil,
    :NodeID => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.NodeUpdateDrainRequest do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:DrainSpec, :struct, Nomad.Model.DrainSpec, options)
  end
end

