# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.OneTimeToken do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AccessorID,
    :CreateIndex,
    :ExpiresAt,
    :ModifyIndex,
    :OneTimeSecretID
  ]

  @type t :: %__MODULE__{
    :AccessorID => String.t | nil,
    :CreateIndex => integer() | nil,
    :ExpiresAt => DateTime.t | nil,
    :ModifyIndex => integer() | nil,
    :OneTimeSecretID => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.OneTimeToken do
  def decode(value, _options) do
    value
  end
end

