# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.OperatorHealthReply do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :FailureTolerance,
    :Healthy,
    :Servers
  ]

  @type t :: %__MODULE__{
    :FailureTolerance => integer() | nil,
    :Healthy => boolean() | nil,
    :Servers => [Nomad.Model.ServerHealth.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.OperatorHealthReply do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Servers, :list, Nomad.Model.ServerHealth, options)
  end
end

