# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ParameterizedJobConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MetaOptional",
    :"MetaRequired",
    :"Payload"
  ]

  @type t :: %__MODULE__{
    :"MetaOptional" => [String.t] | nil,
    :"MetaRequired" => [String.t] | nil,
    :"Payload" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ParameterizedJobConfig do
  def decode(value, _options) do
    value
  end
end

