# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.PeriodicConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Enabled",
    :"ProhibitOverlap",
    :"Spec",
    :"SpecType",
    :"TimeZone"
  ]

  @type t :: %__MODULE__{
    :"Enabled" => boolean() | nil,
    :"ProhibitOverlap" => boolean() | nil,
    :"Spec" => String.t | nil,
    :"SpecType" => String.t | nil,
    :"TimeZone" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.PeriodicConfig do
  def decode(value, _options) do
    value
  end
end

