# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.PointValue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Points"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t | nil,
    :"Points" => [float()] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.PointValue do
  def decode(value, _options) do
    value
  end
end

