# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.Port do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"HostNetwork",
    :"Label",
    :"To",
    :"Value"
  ]

  @type t :: %__MODULE__{
    :"HostNetwork" => String.t | nil,
    :"Label" => String.t | nil,
    :"To" => integer() | nil,
    :"Value" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Port do
  def decode(value, _options) do
    value
  end
end

