# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.QuotaLimit do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Hash,
    :Region,
    :RegionLimit,
    :VariablesLimit
  ]

  @type t :: %__MODULE__{
    :Hash => binary() | nil,
    :Region => String.t | nil,
    :RegionLimit => Nomad.Model.Resources.t | nil,
    :VariablesLimit => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.QuotaLimit do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:RegionLimit, :struct, Nomad.Model.Resources, options)
  end
end

