# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.RaftConfiguration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Index,
    :Servers
  ]

  @type t :: %__MODULE__{
    :Index => integer() | nil,
    :Servers => [Nomad.Model.RaftServer.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.RaftConfiguration do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Servers, :list, Nomad.Model.RaftServer, options)
  end
end

