# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.Resources do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CPU",
    :"Cores",
    :"Devices",
    :"DiskMB",
    :"IOPS",
    :"MemoryMB",
    :"MemoryMaxMB",
    :"Networks"
  ]

  @type t :: %__MODULE__{
    :"CPU" => integer() | nil,
    :"Cores" => integer() | nil,
    :"Devices" => [Nomad.Model.RequestedDevice.t] | nil,
    :"DiskMB" => integer() | nil,
    :"IOPS" => integer() | nil,
    :"MemoryMB" => integer() | nil,
    :"MemoryMaxMB" => integer() | nil,
    :"Networks" => [Nomad.Model.NetworkResource.t] | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Resources do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Devices", :list, Nomad.Model.RequestedDevice, options)
    |> deserialize(:"Networks", :list, Nomad.Model.NetworkResource, options)
  end
end

