# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.RestartPolicy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Attempts",
    :"Delay",
    :"Interval",
    :"Mode"
  ]

  @type t :: %__MODULE__{
    :"Attempts" => integer() | nil,
    :"Delay" => integer() | nil,
    :"Interval" => integer() | nil,
    :"Mode" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.RestartPolicy do
  def decode(value, _options) do
    value
  end
end

