# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ScalingPolicy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CreateIndex",
    :"Enabled",
    :"ID",
    :"Max",
    :"Min",
    :"ModifyIndex",
    :"Namespace",
    :"Policy",
    :"Target",
    :"Type"
  ]

  @type t :: %__MODULE__{
    :"CreateIndex" => integer() | nil,
    :"Enabled" => boolean() | nil,
    :"ID" => String.t | nil,
    :"Max" => integer() | nil,
    :"Min" => integer() | nil,
    :"ModifyIndex" => integer() | nil,
    :"Namespace" => String.t | nil,
    :"Policy" => %{optional(String.t) => AnyType} | nil,
    :"Target" => %{optional(String.t) => String.t} | nil,
    :"Type" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ScalingPolicy do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Policy", :map, Nomad.Model.AnyType, options)
  end
end

