# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ScalingEvent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Count,
    :CreateIndex,
    :Error,
    :EvalID,
    :Message,
    :Meta,
    :PreviousCount,
    :Time
  ]

  @type t :: %__MODULE__{
    :Count => integer() | nil,
    :CreateIndex => integer() | nil,
    :Error => boolean() | nil,
    :EvalID => String.t | nil,
    :Message => String.t | nil,
    :Meta => %{optional(String.t) => any()} | nil,
    :PreviousCount => integer() | nil,
    :Time => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ScalingEvent do
  def decode(value, _options) do
    value
  end
end

