# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ScalingRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Count",
    :"Error",
    :"Message",
    :"Meta",
    :"Namespace",
    :"PolicyOverride",
    :"Region",
    :"SecretID",
    :"Target"
  ]

  @type t :: %__MODULE__{
    :"Count" => integer() | nil,
    :"Error" => boolean() | nil,
    :"Message" => String.t | nil,
    :"Meta" => %{optional(String.t) => AnyType} | nil,
    :"Namespace" => String.t | nil,
    :"PolicyOverride" => boolean() | nil,
    :"Region" => String.t | nil,
    :"SecretID" => String.t | nil,
    :"Target" => %{optional(String.t) => String.t} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ScalingRequest do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Meta", :map, Nomad.Model.AnyType, options)
  end
end

