# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.ScalingEvent do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Count",
    :"CreateIndex",
    :"Error",
    :"EvalID",
    :"Message",
    :"Meta",
    :"PreviousCount",
    :"Time"
  ]

  @type t :: %__MODULE__{
    :"Count" => integer() | nil,
    :"CreateIndex" => integer() | nil,
    :"Error" => boolean() | nil,
    :"EvalID" => String.t | nil,
    :"Message" => String.t | nil,
    :"Meta" => %{optional(String.t) => AnyType} | nil,
    :"PreviousCount" => integer() | nil,
    :"Time" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ScalingEvent do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Meta", :map, Nomad.Model.AnyType, options)
  end
end

