# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ScalingPolicy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CreateIndex,
    :Enabled,
    :ID,
    :Max,
    :Min,
    :ModifyIndex,
    :Namespace,
    :Policy,
    :Target,
    :Type
  ]

  @type t :: %__MODULE__{
    :CreateIndex => integer() | nil,
    :Enabled => boolean() | nil,
    :ID => String.t | nil,
    :Max => integer() | nil,
    :Min => integer() | nil,
    :ModifyIndex => integer() | nil,
    :Namespace => String.t | nil,
    :Policy => %{optional(String.t) => any()} | nil,
    :Target => %{optional(String.t) => String.t} | nil,
    :Type => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ScalingPolicy do
  def decode(value, _options) do
    value
  end
end

