# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.SchedulerConfiguration do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :CreateIndex,
    :MemoryOversubscriptionEnabled,
    :ModifyIndex,
    :PauseEvalBroker,
    :PreemptionConfig,
    :RejectJobRegistration,
    :SchedulerAlgorithm
  ]

  @type t :: %__MODULE__{
    :CreateIndex => integer() | nil,
    :MemoryOversubscriptionEnabled => boolean() | nil,
    :ModifyIndex => integer() | nil,
    :PauseEvalBroker => boolean() | nil,
    :PreemptionConfig => Nomad.Model.PreemptionConfig.t | nil,
    :RejectJobRegistration => boolean() | nil,
    :SchedulerAlgorithm => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SchedulerConfiguration do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PreemptionConfig, :struct, Nomad.Model.PreemptionConfig, options)
  end
end

