# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.SchedulerConfigurationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :KnownLeader,
    :LastContact,
    :LastIndex,
    :NextToken,
    :RequestTime,
    :SchedulerConfig
  ]

  @type t :: %__MODULE__{
    :KnownLeader => boolean() | nil,
    :LastContact => integer() | nil,
    :LastIndex => integer() | nil,
    :NextToken => String.t | nil,
    :RequestTime => integer() | nil,
    :SchedulerConfig => Nomad.Model.SchedulerConfiguration.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SchedulerConfigurationResponse do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SchedulerConfig, :struct, Nomad.Model.SchedulerConfiguration, options)
  end
end

