# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.SchedulerSetConfigurationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :LastIndex,
    :RequestTime,
    :Updated
  ]

  @type t :: %__MODULE__{
    :LastIndex => integer() | nil,
    :RequestTime => integer() | nil,
    :Updated => boolean() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SchedulerSetConfigurationResponse do
  def decode(value, _options) do
    value
  end
end

