# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.SearchRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"AllowStale",
    :"AuthToken",
    :"Context",
    :"Namespace",
    :"NextToken",
    :"Params",
    :"PerPage",
    :"Prefix",
    :"Region",
    :"WaitIndex",
    :"WaitTime"
  ]

  @type t :: %__MODULE__{
    :"AllowStale" => boolean() | nil,
    :"AuthToken" => String.t | nil,
    :"Context" => String.t | nil,
    :"Namespace" => String.t | nil,
    :"NextToken" => String.t | nil,
    :"Params" => %{optional(String.t) => String.t} | nil,
    :"PerPage" => integer() | nil,
    :"Prefix" => String.t | nil,
    :"Region" => String.t | nil,
    :"WaitIndex" => integer() | nil,
    :"WaitTime" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SearchRequest do
  def decode(value, _options) do
    value
  end
end

