# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.SearchResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"KnownLeader",
    :"LastContact",
    :"LastIndex",
    :"Matches",
    :"RequestTime",
    :"Truncations"
  ]

  @type t :: %__MODULE__{
    :"KnownLeader" => boolean() | nil,
    :"LastContact" => integer() | nil,
    :"LastIndex" => integer() | nil,
    :"Matches" => %{optional(String.t) => [String.t]} | nil,
    :"RequestTime" => integer() | nil,
    :"Truncations" => %{optional(String.t) => boolean()} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SearchResponse do
  def decode(value, _options) do
    value
  end
end

