# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.ServiceCheck do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :AddressMode,
    :Advertise,
    :Args,
    :Body,
    :CheckRestart,
    :Command,
    :Expose,
    :FailuresBeforeCritical,
    :GRPCService,
    :GRPCUseTLS,
    :Header,
    :InitialStatus,
    :Interval,
    :Method,
    :Name,
    :OnUpdate,
    :Path,
    :PortLabel,
    :Protocol,
    :SuccessBeforePassing,
    :TLSSkipVerify,
    :TaskName,
    :Timeout,
    :Type
  ]

  @type t :: %__MODULE__{
    :AddressMode => String.t | nil,
    :Advertise => String.t | nil,
    :Args => [String.t] | nil,
    :Body => String.t | nil,
    :CheckRestart => Nomad.Model.CheckRestart.t | nil,
    :Command => String.t | nil,
    :Expose => boolean() | nil,
    :FailuresBeforeCritical => integer() | nil,
    :GRPCService => String.t | nil,
    :GRPCUseTLS => boolean() | nil,
    :Header => %{optional(String.t) => [String.t]} | nil,
    :InitialStatus => String.t | nil,
    :Interval => integer() | nil,
    :Method => String.t | nil,
    :Name => String.t | nil,
    :OnUpdate => String.t | nil,
    :Path => String.t | nil,
    :PortLabel => String.t | nil,
    :Protocol => String.t | nil,
    :SuccessBeforePassing => integer() | nil,
    :TLSSkipVerify => boolean() | nil,
    :TaskName => String.t | nil,
    :Timeout => integer() | nil,
    :Type => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.ServiceCheck do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:CheckRestart, :struct, Nomad.Model.CheckRestart, options)
  end
end

