# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.SidecarTask do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Config,
    :Driver,
    :Env,
    :KillSignal,
    :KillTimeout,
    :LogConfig,
    :Meta,
    :Name,
    :Resources,
    :ShutdownDelay,
    :User
  ]

  @type t :: %__MODULE__{
    :Config => %{optional(String.t) => any()} | nil,
    :Driver => String.t | nil,
    :Env => %{optional(String.t) => String.t} | nil,
    :KillSignal => String.t | nil,
    :KillTimeout => integer() | nil,
    :LogConfig => Nomad.Model.LogConfig.t | nil,
    :Meta => %{optional(String.t) => String.t} | nil,
    :Name => String.t | nil,
    :Resources => Nomad.Model.Resources.t | nil,
    :ShutdownDelay => integer() | nil,
    :User => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SidecarTask do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:LogConfig, :struct, Nomad.Model.LogConfig, options)
    |> deserialize(:Resources, :struct, Nomad.Model.Resources, options)
  end
end

