# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.SpreadTarget do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Percent",
    :"Value"
  ]

  @type t :: %__MODULE__{
    :"Percent" => integer() | nil,
    :"Value" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.SpreadTarget do
  def decode(value, _options) do
    value
  end
end

