# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.Spread do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Attribute,
    :SpreadTarget,
    :Weight
  ]

  @type t :: %__MODULE__{
    :Attribute => String.t | nil,
    :SpreadTarget => [Nomad.Model.SpreadTarget.t] | nil,
    :Weight => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.Spread do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:SpreadTarget, :list, Nomad.Model.SpreadTarget, options)
  end
end

