# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.TaskGroupDiff do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Fields,
    :Name,
    :Objects,
    :Tasks,
    :Type,
    :Updates
  ]

  @type t :: %__MODULE__{
    :Fields => [Nomad.Model.FieldDiff.t] | nil,
    :Name => String.t | nil,
    :Objects => [Nomad.Model.ObjectDiff.t] | nil,
    :Tasks => [Nomad.Model.TaskDiff.t] | nil,
    :Type => String.t | nil,
    :Updates => %{optional(String.t) => integer()} | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.TaskGroupDiff do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Fields, :list, Nomad.Model.FieldDiff, options)
    |> deserialize(:Objects, :list, Nomad.Model.ObjectDiff, options)
    |> deserialize(:Tasks, :list, Nomad.Model.TaskDiff, options)
  end
end

