# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.TaskArtifact do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"GetterHeaders",
    :"GetterMode",
    :"GetterOptions",
    :"GetterSource",
    :"RelativeDest"
  ]

  @type t :: %__MODULE__{
    :"GetterHeaders" => %{optional(String.t) => String.t} | nil,
    :"GetterMode" => String.t | nil,
    :"GetterOptions" => %{optional(String.t) => String.t} | nil,
    :"GetterSource" => String.t | nil,
    :"RelativeDest" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.TaskArtifact do
  def decode(value, _options) do
    value
  end
end

