# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.TaskState do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Events",
    :"Failed",
    :"FinishedAt",
    :"LastRestart",
    :"Restarts",
    :"StartedAt",
    :"State",
    :"TaskHandle"
  ]

  @type t :: %__MODULE__{
    :"Events" => [Nomad.Model.TaskEvent.t] | nil,
    :"Failed" => boolean() | nil,
    :"FinishedAt" => DateTime.t | nil,
    :"LastRestart" => DateTime.t | nil,
    :"Restarts" => integer() | nil,
    :"StartedAt" => DateTime.t | nil,
    :"State" => String.t | nil,
    :"TaskHandle" => Nomad.Model.TaskHandle.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.TaskState do
  import Nomad.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Events", :list, Nomad.Model.TaskEvent, options)
    |> deserialize(:"TaskHandle", :struct, Nomad.Model.TaskHandle, options)
  end
end

