# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.TaskHandle do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DriverState",
    :"Version"
  ]

  @type t :: %__MODULE__{
    :"DriverState" => binary() | nil,
    :"Version" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.TaskHandle do
  def decode(value, _options) do
    value
  end
end

