# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.TaskGroupSummary do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Complete",
    :"Failed",
    :"Lost",
    :"Queued",
    :"Running",
    :"Starting"
  ]

  @type t :: %__MODULE__{
    :"Complete" => integer() | nil,
    :"Failed" => integer() | nil,
    :"Lost" => integer() | nil,
    :"Queued" => integer() | nil,
    :"Running" => integer() | nil,
    :"Starting" => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.TaskGroupSummary do
  def decode(value, _options) do
    value
  end
end

