# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule Nomad.Model.VolumeMount do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Destination",
    :"PropagationMode",
    :"ReadOnly",
    :"Volume"
  ]

  @type t :: %__MODULE__{
    :"Destination" => String.t | nil,
    :"PropagationMode" => String.t | nil,
    :"ReadOnly" => boolean() | nil,
    :"Volume" => String.t | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.VolumeMount do
  def decode(value, _options) do
    value
  end
end

