# NOTE: This file is auto generated by OpenAPI Generator 6.4.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Nomad.Model.WaitConfig do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Max,
    :Min
  ]

  @type t :: %__MODULE__{
    :Max => integer() | nil,
    :Min => integer() | nil
  }
end

defimpl Poison.Decoder, for: Nomad.Model.WaitConfig do
  def decode(value, _options) do
    value
  end
end

